Add narrotive in the enemies drop
3AHAT0P/StrangeTextRPG pull request #47
Opened 2021-05-29 18:48 UTC by alakril

2021-05-29 18:57 UTC, 3AHAT0P requested changes

2021-05-29 18:57 UTC, 3AHAT0P commented on src/locations/ruin/RuinLocation.ts
> +              ); '';
???

2021-05-29 18:57 UTC, 3AHAT0P commented on src/locations/ruin/RuinLocation.ts
> +              player.equipWeapon(new KnifeWeapon('LEGENDARY'));
Я не уверен, что стоит давать легендарное)))

2021-05-29 18:57 UTC, 3AHAT0P commented on src/actors/item/index.ts
> +/* eslint-disable max-classes-per-file */
это тут не нужно)

2021-06-07 17:09 UTC, 3AHAT0P approved these changes

2021-06-08 07:55 UTC, e-sulimenko approved these changes

2021-06-08 18:32 UTC, merged

2021-06-08 18:36 UTC, e-sulimenko approved these changes