Feature/inventory
3AHAT0P/StrangeTextRPG pull request #53
Opened 2021-06-19 13:20 UTC by e-sulimenko

2021-06-19 15:10 UTC, 3AHAT0P requested changes

2021-06-19 15:10 UTC, 3AHAT0P commented on src/actors/armor/index.ts
> +  public readonly baseName = 'шкура';
зачем? у тебя же есть геттер name, публичный

2021-06-19 15:10 UTC, 3AHAT0P commented on src/actors/Player.ts
>    public collectReward(reward: RewardBag): void {
да, этот метод уже не нужен. можем напрямую с инвентарём работать

2021-06-19 15:10 UTC, 3AHAT0P commented on src/actors/miscellaneous/index.ts
> +  public readonly baseName: string = 'крысья шкура';
protected :)

2021-06-24 14:18 UTC, alakril commented on src/actors/AbstractInventory.ts
> +  public useItem(item: AbstractItem, target: AbstractActor): string {
Мне кажется, что тут нужен более универсальный метод, который действует для всех вещей. если у нас 100 зелий в игре, то эта функция просто "лопнет".
В этой функции скорее всего нужно будет только проверять, что выбранная вещи имеет функцию use и у игрока таких вещей больше 0

2021-06-24 14:18 UTC, alakril commented on src/actors/AbstractActor.ts
> +  public getReward(player: AbstractActor): string { return ''; }
эту функцию я бы тоже из этого класса вынес. хотя у скелетов тоже может быть хорошо оплачиваемая работа...

2021-06-24 14:18 UTC, alakril commented on src/actors/potions/index.ts
> +export class SmallHealthPotion extends HealthPotion {
хмм... стоит ли создавать для каждого зелья лечения свой итем?..
по идее можно оставить только HealthPotion, в конструторе которого задаётся его субтайп, дописывается имя и задаётся сколько лечит. Как с редкостью оружия. По сути это одно и то же.

2021-06-24 14:18 UTC, alakril commented on src/interactions/BattleInteraction.ts
> +  // useHealthPoition: 'Использовать зелье лечения',
ох уж эти комментарии)

2021-06-24 14:18 UTC, alakril commented on src/interactions/BattleInteraction.ts
> +  // useHealthPoition: 'Использовать зелье лечения',
и вы всё таки решили вынести это из битвы?

2021-06-24 14:18 UTC, alakril commented on src/interactions/NPC/Merchant.ts
>        const i3 = new Interaction({
аргххх... не к тебе вопрос, но зачем так больно называть переменные?

2021-06-24 14:18 UTC, alakril commented on src/locations/ruin/RuinLocation.ts
> +  private async showInventory(): Promise<void> {
это бы вынести куда-то более глобально, а то получается, что в инвентарь можем только в локации руин смотреть...

2021-06-24 14:18 UTC, alakril commented on src/locations/ruin/RuinLocation.ts
> +              player.inventory.collectItem(new KnifeWeapon());
Уточнить: получается мы только подбираем нож, а надевать его уже в инвентаре нужно, правильно?

2021-06-24 14:18 UTC, alakril commented on src/locations/ruin/RuinLocation.ts
> +            action: 'Купить',
Нужен ли action у NPC если все товары - купить

2021-06-25 05:22 UTC, 3AHAT0P commented on src/actors/AbstractActor.ts
> +  public exchangeGoldToItem(goldCount: number, items: AbstractItem[]) { return false; }
Ага)))
А вообще, нужно просто разделить интерфейсы (Player, NPC, Mob) только пока не совсем понятно как. И что у каждого должно быть

2021-06-25 05:22 UTC, 3AHAT0P commented on src/actors/AbstractActor.ts
> +  public exchangeGoldToItem(goldCount: number, items: AbstractItem[]) { return false; }
поэтому пусть этот тут полежит

2021-06-25 05:23 UTC, 3AHAT0P commented on src/actors/AbstractInventory.ts
> +  public useItem(item: AbstractItem, target: AbstractActor): string {
согласен :)

2021-06-25 05:24 UTC, 3AHAT0P commented on src/actors/AbstractActor.ts
> +  public getReward(player: AbstractActor): string { return ''; }
Ага)))
А вообще, нужно просто разделить интерфейсы (Player, NPC, Mob) только пока не совсем понятно как. И что у каждого должно быть
поэтому пусть этот тут полежит

2021-06-25 05:25 UTC, 3AHAT0P commented on src/actors/potions/index.ts
> +export class SmallHealthPotion extends HealthPotion {
Да, звучит логично.

2021-06-25 05:26 UTC, 3AHAT0P commented on src/interactions/BattleInteraction.ts
> +  // useHealthPoition: 'Использовать зелье лечения',
У игрока будет возможность открыть инвентарь. не важно в битве он или нет. А оттуда он сможет сделать все что нужно

2021-06-25 05:27 UTC, 3AHAT0P commented on src/interactions/NPC/Merchant.ts
>        const i3 = new Interaction({
))))
Потому что они никакой смысловой нагрузки не несут, кроме как для связей.
К тому, же i - interaction а число указывает на interactionId

2021-06-25 05:28 UTC, 3AHAT0P commented on src/interactions/NPC/Merchant.ts
>        const i3 = new Interaction({
в некоторых местах таких переменных будет очень много (20, 50, 100) и каждому давать очень персональное название - можно устать. А при связывании все равно не особо поможет

2021-06-25 05:29 UTC, 3AHAT0P commented on src/locations/ruin/RuinLocation.ts
> +  private async showInventory(): Promise<void> {
да. Но это не в этой задаче

2021-06-25 05:29 UTC, 3AHAT0P commented on src/locations/ruin/RuinLocation.ts
> +              player.inventory.collectItem(new KnifeWeapon());
именно так!

2021-06-25 05:33 UTC, 3AHAT0P commented on src/locations/ruin/RuinLocation.ts
> +            action: 'Купить',
Тут все сложно. 
Во-первых, торговец может еще и покупать.
Во-вторых, может быть обмен вещей.
В-третьих, это все немного обновится в ПР с БД.

Поэтому тут на это забиваем.

2021-06-25 05:34 UTC, 3AHAT0P commented on src/locations/ruin/RuinLocation.ts
> +            action: 'Купить',
но, мысль хорошая)

2021-06-25 10:04 UTC, alakril commented on src/actors/AbstractActor.ts
> +  public exchangeGoldToItem(goldCount: number, items: AbstractItem[]) { return false; }
главное потом не заб(ы/и)ть

2021-06-28 08:16 UTC, 3AHAT0P commented on src/actors/AbstractInventory.ts
> +import {HealthPotion, Potion} from '@actors/potions';
пробельчики

2021-06-28 08:19 UTC, 3AHAT0P approved these changes

2021-07-06 07:31 UTC, merged